version: "3.3"

services:
  chat-app-backend:
    image: chat-app-backend:1.0.0
    build: .
    ports:
      - "5000:5000"
    environment:
      - EXTERNAL_PORT=5000
      - PGUSER=abhiram
      - PGPASSWORD=12345
      - PGDATABASE=chat_db
      - PGHOST=chat-database
    depends_on:
      - chat-database

  chat-database:
    container_name: chat-database
    image: "postgres:14"
    ports:
      - "5432-5432"
    environment:
      - POSTGRES_USER=abhiram
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=chat_db
    volumes:
      - chat_data:/var/lib/postgresql/database

volumes:
  chat_data: {}
