version: "3.3"

services:
  boiler-plate:
    image: boiler-plate:1.0.0
    build: .
    ports:
      - "5000:5000"
    environment:
      - EXTERNAL_PORT=5000
      - PGUSER=abhiram
      - PGPASSWORD=12345
      - PGDATABASE=boiler_db
      - PGHOST=boiler-database
    depends_on:
      - boiler-database

  boiler-database:
    container_name: boiler-database
    image: "postgres:14"
    ports:
      - "5432-5432"
    environment:
      - POSTGRES_USER=abhiram
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=boiler_db
    volumes:
      - boiler_data:/var/lib/postgresql/database

volumes:
  boiler_data: {}
