version: "3.3"

services:
  boiler-plate:
    image: boiler-plate:1.0.0
    build: .
    ports:
      - "5001:5001"
    volumes:
      - .:/app
      - /app/node_modules 
    environment:
      - EXTERNAL_PORT=5001
      - PGUSER=abhiram
      - PGPASSWORD=12345
      - PGDATABASE=boiler_db
      - PGHOST=boiler-database
    depends_on:
      - boiler-database

  boiler-database:
    container_name: boiler-database
    image: "postgres:14"
    ports:
      - "5432-5432"
    environment:
      - POSTGRES_USER=abhiram
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=boiler_db
    volumes:
      - ./data:/var/lib/postgresql/data


